### ISSUE TITLE
Train.py is taking time

### ISSUE THREAD

**Issue by dkrathi457** [bluer555/CR-GAN#6]
I am just running the train.py code to train the model on the dataset you provided. But still spending three hours there is no change in status, its showing just total number of images. can you tell me how long it will take.

**Comment by fishzhouz** [comment]
Did you meet this issues."RuntimeError: CUDA error:out of memory"?

**Comment by fishzhouz** [comment]
Did you meet this problem."RuntimeError: CUDA error:out of memory"?

**Comment by HJ0Wang** [comment]
I met the same error. It's not "RuntimeError: CUDA error:out of memory". When I run the train.py, the code gets stuck at line 138, "for i, (view1, view2, data1, data2) in enumerate(train_loader):" (there only prints "total 120000 images", no more information shown). I have added  "print('i, (view1, view2, data1, data2)',i, (view1, view2, data1, data2))" at line 139, but it doesn't work (no information about i and (view1, view2, data1, data2) has been printed). I think that there's something wrong with the train_loader, because I can't print 'list(enumerate(train_loader))'.  My environment : python2.7 + pytorch 0.3.1 + torchvision 0.2.1

**Comment by HJ0Wang** [comment]
The problem is solved. I make a mistake that I didn't download the 300w_LP_size_128 file, so the code got stuck at line76: train_loader.

**Comment by Loydian** [comment]
@HJ0Wang The original download link is unavailable. Can you send a copy or download link to loydian@foxmail.com? It's really important for me. I can't thank you enough.

**Comment by HJ0Wang** [comment]
The 300W LP download link is: 
https://drive.google.com/file/d/0B7OEHD3T4eCkVGs0TkhUWFN6N1k/view?resourcekey=0-WT5tO4TOCbNZY6r6z6WmOA

FYI

**Comment by Loydian** [comment]
@HJ0Wang Words cannot express how thankful I am. It is very kind of you to reply me so quickly. It's really helping. And I wonder if you have the txt file accompanied with the dataset. The original download link is also unavailable. Sorry for bothering you again.
